id: I05B611FA
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T18:34:08+00:00'
last_modified: '2022-06-08T01:53:39.280401+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG13122
  title: བོད་ཀྱི་ལོ་རྒྱུས་རྣམ་ཐར་ཕྱོགས་བསྒྲིགས་ཀྱི་དཀར་ཆག
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    '8308':
      image_group_id: I1KG13480
      title: ''
      total_pages: 198
      order: 1
      base_file: 8308.txt
    A51E:
      image_group_id: I1KG13481
      title: ''
      total_pages: 252
      order: 2
      base_file: A51E.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
